-- ToME4 korean Translation addon
-- utility functions for korean Translation 
-- 사용하려는 파일마다 상단부에 명령 추가 필요 : require "engine.krtrUtils" 

function string.addJosa(str, temp)
	local josa1, josa2, index

	if temp == 1 or temp == "가" or temp == "이" then
		josa1 = "가"
		josa2 = "이"
		index = 1
	elseif temp == 2 or temp == "는" or temp == "은" then
		josa1 = "는"
		josa2 = "은"
		index = 2
	elseif temp == 3 or temp == "를" or temp == "을" then
		josa1 = "를"
		josa2 = "을"
		index = 3
	elseif temp == 4 or temp == "로" or temp == "으로" then
		josa1 = "로"
		josa2 = "으로"
		index = 4
	elseif temp == 5 or temp == "다" or temp == "이다" then
		josa1 = "다"
		josa2 = "이다"
		index = 5
	elseif temp == 6 or temp == "와" or temp == "과" then
		josa1 = "와"
		josa2 = "과"
		index = 6
	else
		if type(temp) == string then return str .. temp
		else return str end 
	end

	local length = str:len()
	
	if length < 3 then
		return str .. josa2
	end
	
	local c1 = str:byte(length-2)
	local c2 = str:byte(length-1)
	local c3 = str:byte(length)
	
	local last = ( (c1-234)*4096 + (c2-128)*64 + (c3-128) - 3072 )%28
	
	if last == 0 or ( index == 4 and last == 8 ) then
		return str .. josa1
	else
		return str .. josa2
	end
end

function string.krStat(engStat)
	local ori = engStat:lower()
	if ori == "strength" or ori == "str" then return "힘"
	elseif ori == "dexterity" or ori == "dex" then return "민첩"
	elseif ori == "constitution" or ori == "con" then return "체격"
	elseif ori == "magic" or ori == "mag" then return "마법"
	elseif ori == "willpower" or ori == "wil" then return "의지"
	elseif ori == "cunning" then return "교활함"
	elseif ori == "cun" then return "교활"
	elseif ori == "luck" or ori == "lck" then return "행운"
	else return engStat end
end

function string.krDamageType(str)
	local ori = str:lower()
	if ori == "physical" then return "물리"
	elseif ori == "arcane" then return "마법"
	elseif ori == "fire" then return "화염"
	elseif ori == "cold" then return "추위"
	elseif ori == "lightning" then return "전기"
	elseif ori == "acid" then return "산성"
	elseif ori == "nature" then return "자연"
	elseif ori == "blight" then return "황폐"
	elseif ori == "light" then return "빛"
	elseif ori == "darkness" then return "어둠"
	elseif ori == "mind" then return "정신"
	elseif ori == "temporal" then return "시간"
	elseif ori == "lite" then return "조명"
	elseif ori == "silence" then return "침묵"
	elseif ori == "poison" then return "중독"
	elseif ori == "inferno" then return "열화"
	elseif ori == "bleed" then return "출혈"
	elseif ori == "slime" then return "슬라임"
	elseif ori == "dig" then return "굴착"
	elseif ori == "slow" then return "감속"
	elseif ori == "confusion" then return "혼돈"
	elseif ori == "sand" then return "수면"
	elseif ori == "pinning" then return "속박"
	elseif ori == "blindness" then return "실명"
	elseif ori == "ice" then return "냉동"
	elseif ori == "freeze" then return "빙결"
	elseif ori == "healing" then return "회복"
	elseif ori == "matter" then return "물질"
	elseif ori == "void" then return "공허"
	elseif ori == "gravity" then return "중력"
	elseif ori == "temporalstun" then return "시간적 기절"
	elseif ori == "break stealth" then return "은신해제"
	elseif ori == "arcane silence" then return "마법적 침묵"
	elseif ori == "% chance to silence target" then return "% 확률적 침묵"
	elseif ori == "blinding ink" then return "눈가리기"
	elseif ori == "bright light" then return "빛의 조명"
	elseif ori == "fire burn" then return "지속형 화염"
	elseif ori == "fireburn" then return "지속형 화염"
	elseif ori == "shadowflame" then return "어두운 화염"
	elseif ori == "darkstun" then return "암흑의 기절"
	elseif ori == "minions darkness" then return "어둠의 소환수"
	elseif ori == "firey no friends" then return "화염"
	elseif ori == "coldstun" then return "추위로 기절"
	elseif ori == "flameshock" then return "뜨거운 기절"
	elseif ori == "coldnevermove" then return "얼림"
	elseif ori == "sticky smoke" then return "끈적이는 연기"
	elseif ori == "acid blind" then return "신성 실명"
	elseif ori == "blinding darkness" then return "실명의 어둠"
	elseif ori == "lightning daze" then return "전기로 혼절"
	elseif ori == "wave" then return "파동"
	elseif ori == "fire knockback" then return "밀어내기 화염"
	elseif ori == "fire knockback mind" then return "정신적 밀어내기 화염"
	elseif ori == "darkness knockback" then return "밀어내기 어둠"
	elseif ori == "spell knockback" then return "밀어내기 주문"
	elseif ori == "mind knockback" then return "밀어내기 정신"
	elseif ori == "physknockback" then return "밀어내기 물리"
	elseif ori == "fear knockback" then return "밀어내기 공포"
	elseif ori == "spydric poison" then return "속박형 중독"
	elseif ori == "crippling poison" then return "장애형 중독"
	elseif ori == "insidious poison" then return "반회복형 중독"
	elseif ori == "physical + bleeding" then return "물리 + 출혈"
	elseif ori == "congeal time" then return "시간 멈춤"
	elseif ori == "time prison" then return "시간의 감옥"
	elseif ori == "% chances to confuse" then return "% 확률적 혼돈"
	elseif ori == "% chances to cause a gloom effect" then return "% 확률적 침울"
	elseif ori == "% chances to blind" then return "% 확률적 실명"
	elseif ori == "drain experience" then return "경험치 감소"
	elseif ori == "drain life" then return "생명력 감소"
	elseif ori == "drain vim" then return "정력 감소"
	elseif ori == "demonfire" then return "악마의 불길"
	elseif ori == "retch" then return "구역질"
	elseif ori == "holy light" then return "성스런 빛"
	elseif ori == "healing power" then return "회복력"
	elseif ori == "healing nature" then return "자연적 회복"
	elseif ori == "corrupted blood" then return "타락한 피"
	elseif ori == "blood boil" then return "끓는 피"
	elseif ori == "life leech" then return "생명력 강탈"
	elseif ori == "physical stun" then return "물리적 기절"
	elseif ori == "split bleed" then return "피 튀기기"
	elseif ori == "gravity pin" then return "중력적 속박"
	elseif ori == "repulsion" then return "혐오"
	elseif ori == "grow" then return "성장"
	elseif ori == "sanctity" then return "신성"
	elseif ori == "shiftingshadows" then return "그림자변형"
	elseif ori == "blazinglight" then return "타오르는 빛"
	elseif ori == "warding" then return "보호"
	elseif ori == "mindslow" then return "정신적 감속"
	elseif ori == "mindfreeze" then return "정신적 빙결"
	elseif ori == "implosion" then return "파열"
	elseif ori == "reverse aging" then return "젊어짐"
	elseif ori == "wasting" then return "낭비"
	elseif ori == "stop" then return "멈춤"
	elseif ori == "rethread" then return "재구축"
	elseif ori == "temporal echo" then return "시간의 메아리"
	elseif ori == "devour life" then return "생명력 먹어치우기"
	elseif ori == "chronoslow" then return "시간의 느려짐"
	elseif ori == "molten rock" then return "녹아내리는 바위"
	elseif ori == "entangle" then return "얽힘"
	elseif ori == "manaworm" then return "마나벌레"
	elseif ori == "void blast" then return "공허의 돌풍"
	elseif ori == "circle of death" then return "죽음의 고리"
	elseif ori == "rigor mortis" then return "사후 경직"
	elseif ori == "abyssal shroud" then return "심연의 덮개"
	elseif ori == "% chance to summon an orc spirit" then return "% 확률적 오크 정신체 소환"
	elseif ori == "nightmare" then return "악몽"
	elseif ori == "weakness" then return "허약"
	elseif ori == "temp effect" then return "일시적 효과"
	elseif ori == "manaburn" then return "마나태우기"
	elseif ori == "leaves" then return "나뭇잎"
	elseif ori == "distortion" then return "왜곡"
	elseif ori == "dreamforge" then return "꿈의 제조"
	elseif ori == "mucus" then return "점액"
	elseif ori == "acid disarm" then return "산성 무장해제"
	elseif ori == "corrosive acid" then return "산성 부식"
	elseif ori == "bouncing slime" then return "활발한 슬라임"
	else return str end
end

function string.krItemType(str)
	local ori = str:lower()
	if ori == "weapon" then return "무기"
	elseif ori == "armor" then return "갑옷"
	elseif ori == "tool" then return "도구"
	elseif ori == "misc" then return "기타"
	elseif ori == "gem" then return "보석"
	elseif ori == "jewelry" then return "장신구"
	elseif ori == "lite" then return "조명"
	elseif ori == "money" then return "금화"
	elseif ori == "mount" then return "탈것"
	elseif ori == "potion" then return "물약"
	elseif ori == "charm" then return "부적"
	elseif ori == "scroll" then return "마법기"
	elseif ori == "orb" then return "오브"
	elseif ori == "chest" then return "상자"
	elseif ori == "inscription" then return "각인"
	-- 위는 type, 아래는 subtype
	elseif ori == "battleaxe" then return "대형도끼"
	elseif ori == "greatmaul" then return "대형망치"
	elseif ori == "greatsword" then return "대검"
	elseif ori == "trident" then return "삼지창"
	elseif ori == "waraxe" then return "도끼"
	elseif ori == "longbow" then return "활"
	elseif ori == "cloak" then return "망토"
	elseif ori == "cloth" then return "의류"
	elseif ori == "digger" then return "곡괭이"
	elseif ori == "ingredient" then return "연금술재료"
	elseif ori == "hands" then return "장갑"
	elseif ori == "white" then return "흰색"
	elseif ori == "red" then return "붉은색"
	elseif ori == "yellow" then return "노란색"
	elseif ori == "green" then return "녹색"
	elseif ori == "blue" then return "파란색"
	elseif ori == "black" then return "검은색"
	elseif ori == "violet" then return "보라색"
	elseif ori == "heavy" then return "중갑"
	elseif ori == "feet" then return "신발"
	elseif ori == "head" then return "모자"
	elseif ori == "ring" then return "반지"
	elseif ori == "amulet" then return "목걸이"
	elseif ori == "dagger" then return "단검"
	elseif ori == "belt" then return "허리띠"
	elseif ori == "light" then return "경갑"
	elseif ori == "mace" then return "철퇴"
	elseif ori == "massive" then return "판갑"
	elseif ori == "mindstar" then return "마석"
	elseif ori == "golem" then return "골렘"
	elseif ori == "mummy" then return "미라붕대"
	elseif ori == "shield" then return "방패"
	elseif ori == "sling" then return "투석구"
	elseif ori == "staff" then return "마법지팡이"
	elseif ori == "longsword" then return "장검"
	elseif ori == "rod" then return "장대"
	elseif ori == "torque" then return "주술고리"
	elseif ori == "totem" then return "토템"
	elseif ori == "wand" then return "마법막대"
	elseif ori == "whip" then return "채찍"
	elseif ori == "infusion" then return "인퓨전"
	elseif ori == "rune" then return "룬"
	elseif ori == "taint" then return "얼룩"
	elseif ori == "sher'tul" then return "쉐르툴"
	else return str end
end

function string.krTalent(str)
	local ori = str:lower()
	
	-- tutorial
	if ori == "mana gale" then return "마나폭발"
	elseif ori == "telekinetic punt" then return "염동펀치"
	elseif ori == "blink" then return "블링크"
	elseif ori == "fear" then return "공포"
	elseif ori == "bleed" then return "출혈"
	elseif ori == "confusion" then return "혼돈"
	-- misc
	elseif ori == "attack" then return "공격"
	elseif ori == "relentless pursuit" then return "사정없는 추적"
	elseif ori == "disarm" then return "무장해제"
	-- celestial
	elseif ori == "chant of fortitude" then return "인내의 찬가"
	elseif ori == "chant of fortress" then return "보루의 찬가"
	elseif ori == "chant of resistance" then return "저항의 찬가"
	elseif ori == "chant of light" then return "빛의 찬가"
	elseif ori == "circle of shifting shadows" then return "뒤바뀌는 그림자의 권역"
	elseif ori == "circle of blazing light" then return "타오르는 빛의 권역"
	elseif ori == "circle of sanctity" then return "고결함의 권역"
	elseif ori == "circle of warding" then return "배척의 권역"
	elseif ori == "weapon of light" then return "빛의 무기"
	elseif ori == "martyrdom" then return "고난"
	elseif ori == "wave of power" then return "힘의 파동"
	elseif ori == "crusade" then return "박멸"
	elseif ori == "blood red moon" then return "핏빛 달"
	elseif ori == "totality" then return "개기 일월식"
	elseif ori == "corona" then return "코로나"
	elseif ori == "darkest light" then return "가장 어두운 빛"
	elseif ori == "glyph of paralysis" then return "마비의 문양"
	elseif ori == "glyph of repulsion" then return "격퇴의 문양"
	elseif ori == "glyph of explosion" then return "폭발의 문양"
	elseif ori == "glyph of fatigue" then return "피로의 문양"
	elseif ori == "shield of light" then return "빛의 방패"
	elseif ori == "brandish" then return "광휘"
	elseif ori == "retribution" then return "응보"
	elseif ori == "second life" then return "두번째 생명"
	elseif ori == "hymn of shadows" then return "그림자의 송가"
	elseif ori == "hymn of detection" then return "간파의 송가"
	elseif ori == "hymn of perseverance" then return "불굴의 송가"
	elseif ori == "hymn of moonlight" then return "달빛의 송가"
	elseif ori == "healing light" then return "치유의 빛"
	elseif ori == "bathe in light" then return "빛의 세례"
	elseif ori == "barrier" then return "방벽"
	elseif ori == "providence" then return "빛의 뜻"
	elseif ori == "moonlight ray" then return "한 줄기 달빛"
	elseif ori == "shadow blast" then return "그림자 확산"
	elseif ori == "twilight surge" then return "밀려드는 황혼"
	elseif ori == "starfall" then return "별똥별"
	elseif ori == "searing light" then return "타오르는 빛"
	elseif ori == "sun flare" then return "태양의 섬광"
	elseif ori == "firebeam" then return "태양의 불길"
	elseif ori == "sunburst" then return "태양 파열"
	elseif ori == "twilight" then return "황혼"
	elseif ori == "jumpgate: teleport to" then return "도약문: 이동"
	elseif ori == "jumpgate" then return "도약문"
	elseif ori == "mind blast" then return "정신 붕괴"
	elseif ori == "Shadow Simulacrum" then return "그림자 투영"
	elseif ori == "jumpgate two: teleport to" then return "두번째 도약문: 이동"
	elseif ori == "jumpgate two" then return "두번째 도약문"
	-- techniques
	elseif ori == "death dance" then return "죽음의 춤"
	elseif ori == "berserker" then return "광전사"
	elseif ori == "warshout" then return "전투의 외침"
	elseif ori == "death blow" then return "죽음의 일격"
	elseif ori == "stunning blow" then return "기절시키기"
	elseif ori == "sunder armour" then return "방어구 부수기"
	elseif ori == "sunder arms" then return "무기 부수기"
	elseif ori == "blood frenzy" then return "피의 광란"
	elseif ori == "shoot" then return "사격"
	elseif ori == "reload" then return "재장전"
	elseif ori == "steady shot" then return "정밀 사격"
	elseif ori == "aim" then return "조준"
	elseif ori == "rapid shot" then return "속사"
	elseif ori == "relaxed shot" then return "힘빼고 쏘기"
	elseif ori == "flare" then return "조명 사격"
	elseif ori == "crippling shot" then return "장애유발 사격"
	elseif ori == "pinning shot" then return "속박 사격"
	elseif ori == "scatter shot" then return "산탄 사격"
	elseif ori == "greater weapon focus" then return "고도의 집중 공격"
	elseif ori == "step up" then return "진격"
	elseif ori == "bleeding edge" then return "출혈상"
	elseif ori == "true gift" then return "진정한 용기"
	elseif ori == "bloodbath" then return "피바다"
	elseif ori == "mortal terror" then return "죽음의 공포"
	elseif ori == "bloodrage" then return "피의 분노"
	elseif ori == "unstoppable" then return "무쌍"
	elseif ori == "bow mastery" then return "활 숙련"
	elseif ori == "piercing arrow" then return "관통 사격"
	elseif ori == "dual arrows" then return "이중 사격"
	elseif ori == "volley of arrows" then return "연발 사격"
	elseif ori == "rush" then return "돌진"
	elseif ori == "precise strikes" then return "정밀 타격"
	elseif ori == "perfect strike" then return "완벽한 타격"
	elseif ori == "blinding speed" then return "불감 속도"
	elseif ori == "quick recovery" then return "빠른 회복"
	elseif ori == "fast metabolism" then return "빠른 신진대사"
	elseif ori == "spell shield" then return "주문 방어막"
	elseif ori == "unending frenzy" then return "끝나지않는 광란"
	elseif ori == "thick skin" then return "튼튼한 피부"
	elseif ori == "armour training" then return "방어구 숙련"
	elseif ori == "combat accuracy" then return "정확한 전투"
	elseif ori == "weapons mastery" then return "무기 숙련"
	elseif ori == "dagger mastery" then return "단검 숙련"
	elseif ori == "exotic weapons mastery" then return "이형무기 숙련"
	elseif ori == "vitality" then return "활력"
	elseif ori == "daunting presence" then return "위협적인 존재감"
	elseif ori == "unflinching resolve" then return "단호한 결의"
	elseif ori == "adrenaline surge" then return "솟구치는 아드레날린"
	elseif ori == "dual weapon training" then return "쌍수 무기 숙련"
	elseif ori == "dual weapon defense" then return "쌍수 무기 방어술"
	elseif ori == "precision" then return "허점 포착"
	elseif ori == "momentum" then return "공격 가속"
	elseif ori == "dual strike" then return "이중 타격"
	elseif ori == "flurry" then return "질풍"
	elseif ori == "sweep" then return "휩쓸기"
	elseif ori == "whirlwind" then return "회오리"
	elseif ori == "disengage" then return "전투 회피"
	elseif ori == "track" then return "추적"
	elseif ori == "heave" then return "밀어차기"
	elseif ori == "slow motion" then return "발사체 포착"
	elseif ori == "uppercut" then return "올려치기"
	elseif ori == "concussive punch" then return "충격타"
	elseif ori == "body shot" then return "몸통 치기"
	elseif ori == "haymaker" then return "죽음의 강타"
	elseif ori == "grappling stance" then return "잡기 자세"
	elseif ori == "clinch" then return "붙잡기"
	elseif ori == "maim" then return "꺾기"
	elseif ori == "crushing hold" then return "눌러 조르기"
	elseif ori == "take down" then return "넘어뜨리기"
	elseif ori == "arcane combat" then return "마법 전투"
	elseif ori == "arcane cunning" then return "교활함의 마법"
	elseif ori == "arcane feed" then return "마력 공급"
	elseif ori == "arcane destruction" then return "마력 폭발"
	elseif ori == "hack'n'back" then return "치고 빠지기"
	elseif ori == "mobile defence" then return "기동 회피"
	elseif ori == "light of foot" then return "가벼운 발놀림"
	elseif ori == "strider" then return "파발꾼"
	elseif ori == "striking stance" then return "타격 자세"
	elseif ori == "double strike" then return "두번 치기"
	elseif ori == "relentless strikes" then return "무자비한 타격"
	elseif ori == "spinning backhand" then return "회전하며 손등치기"
	elseif ori == "flurry of fists" then return "돌풍치기"
	elseif ori == "sling mastery" then return "투석구 숙련"
	elseif ori == "eye shot" then return "눈 맞추기"
	elseif ori == "inertial shot" then return "밀어내기 사격"
	elseif ori == "multishot" then return "여러발 쏘기"
	elseif ori == "juggernaut" then return "거대함"
	elseif ori == "onslaught" then return "맹습"
	elseif ori == "battle call" then return "전장의 부름"
	elseif ori == "shattering impact" then return "충격 흩뿌리기"
	elseif ori == "skullcracker" then return "두개골 부수기"
	elseif ori == "riot-born" then return "폭동에서 태어난자"
	elseif ori == "vicious strikes" then return "잔인한 타격"
	elseif ori == "total thuggery" then return "총 공격"
	elseif ori == "push kick" then return "밀어차기"
	elseif ori == "defensive throw" then return "공격자 넘어뜨리기"
	elseif ori == "breath control" then return "호흡 조절"
	elseif ori == "roundhouse kick" then return "돌려차기"
	elseif ori == "empty hand" then return "맨손 격투술"
	elseif ori == "unarmed mastery" then return "맨손 격투 숙련"
	elseif ori == "steady mind" then return "확고한 정신"
	elseif ori == "heightened reflexes" then return "향상산 반사신경"
	elseif ori == "combo string" then return "연계기"
	elseif ori == "shattering shout" then return "공격의 외침"
	elseif ori == "second wind" then return "제2호흡"
	elseif ori == "battle shout" then return "전장의 외침"
	elseif ori == "battle cry" then return "전장의 포효"
	elseif ori == "shield pummel" then return "방패 치기"
	elseif ori == "riposte" then return "방패 반격"
	elseif ori == "overpower" then return "과도한힘"
	elseif ori == "assault" then return "가격"
	elseif ori == "shield wall" then return "방패의 벽"
	elseif ori == "repulsion" then return "반발"
	elseif ori == "shield expertise" then return "방패 전문가"
	elseif ori == "last stand" then return "끝까지 버티기"
	
	--@@ 여기부터는 필요없는 코드: 아랫부분 번역시 그 아래로 이동, 모두 번역시 삭제
	else return str end
	if false then
	--@@ 여기까지
	
	-- cunning
	elseif ori == "stealth" then return ""
	elseif ori == "shadowstrike" then return ""
	elseif ori == "hide in plain sight" then return ""
	elseif ori == "unseen actions" then return ""
	elseif ori == "trap mastery" then return ""
	elseif ori == "lure" then return ""
	elseif ori == "sticky smoke" then return ""
	elseif ori == "trap launcher" then return ""
	elseif ori == "explosion trap" then return ""
	elseif ori == "bear trap" then return ""
	elseif ori == "catapult trap" then return ""
	elseif ori == "disarming trap" then return ""
	elseif ori == "nightshade trap" then return ""
	elseif ori == "flash bang trap" then return ""
	elseif ori == "poison gas trap" then return ""
	elseif ori == "vile poisons" then return ""
	elseif ori == "venomous strike" then return ""
	elseif ori == "empower poisons" then return ""
	elseif ori == "toxic death" then return ""
	elseif ori == "deadly poison" then return ""
	elseif ori == "numbing poison" then return ""
	elseif ori == "insidious poison" then return ""
	elseif ori == "crippling poison" then return ""
	elseif ori == "stoning poison" then return ""
	elseif ori == "dirty fighting" then return ""
	elseif ori == "backstab" then return ""
	elseif ori == "switch place" then return ""
	elseif ori == "cripple" then return ""
	elseif ori == "lethality" then return ""
	elseif ori == "deadly strikes" then return ""
	elseif ori == "willful combat" then return ""
	elseif ori == "snap" then return ""
	elseif ori == "shadow combat" then return ""
	elseif ori == "shadow cunning" then return ""
	elseif ori == "shadow feed" then return ""
	elseif ori == "shadowstep" then return ""
	elseif ori == "shadow leash" then return ""
	elseif ori == "shadow ambush" then return ""
	elseif ori == "ambuscade" then return ""
	elseif ori == "shadow veil" then return ""
	elseif ori == "trap handling" then return ""
	elseif ori == "heightened senses" then return ""
	elseif ori == "piercing sight" then return ""
	elseif ori == "evasion" then return ""
	elseif ori == "tactical expert" then return ""
	elseif ori == "counter attack" then return ""
	elseif ori == "set up" then return ""
	elseif ori == "exploit weakness" then return ""
	elseif ori == "lacerating strikes" then return ""
	elseif ori == "scoundrel's strategies" then return ""
	elseif ori == "nimble movements" then return ""
	elseif ori == "misdirection" then return ""
	-- spell
	elseif ori == "arcane power" then return ""
	elseif ori == "manathrust" then return ""
	elseif ori == "arcane vortex" then return ""
	elseif ori == "disruption shield" then return ""
	elseif ori == "aether beam" then return ""
	elseif ori == "aether breach" then return ""
	elseif ori == "aether avatar" then return ""
	elseif ori == "pure aether" then return ""
	elseif ori == "flame" then return ""
	elseif ori == "flameshock" then return ""
	elseif ori == "fireflash" then return ""
	elseif ori == "inferno" then return ""
	elseif ori == "blastwave" then return ""
	elseif ori == "burning wake" then return ""
	elseif ori == "cleansing flames" then return ""
	elseif ori == "wildfire" then return ""
	elseif ori == "stone skin" then return ""
	elseif ori == "mudslide" then return ""
	elseif ori == "dig" then return ""
	elseif ori == "stone wall" then return ""
	elseif ori == "earthen missiles" then return ""
	elseif ori == "body of stone" then return ""
	elseif ori == "earthquake" then return ""
	elseif ori == "crystalline focus" then return ""
	elseif ori == "glacial vapour" then return ""
	elseif ori == "freeze" then return ""
	elseif ori == "tidal wave" then return ""
	elseif ori == "ice storm" then return ""
	elseif ori == "ice shards" then return ""
	elseif ori == "frozen ground" then return ""
	elseif ori == "shatter" then return ""
	elseif ori == "uttercold" then return ""
	elseif ori == "lightning" then return ""
	elseif ori == "chain lightning" then return ""
	elseif ori == "feather wind" then return ""
	elseif ori == "thunderstorm" then return ""
	elseif ori == "nova" then return ""
	elseif ori == "shock" then return ""
	elseif ori == "hurricane" then return ""
	elseif ori == "tempest" then return ""
	elseif ori == "disperse magic" then return ""
	elseif ori == "spellcraft" then return ""
	elseif ori == "quicken spells" then return ""
	elseif ori == "metaflow" then return ""
	elseif ori == "congeal time" then return ""
	elseif ori == "time shield" then return ""
	elseif ori == "time prison" then return ""
	elseif ori == "essence of speed" then return ""
	elseif ori == "illuminate" then return ""
	elseif ori == "blur sight" then return ""
	elseif ori == "phantasmal shield" then return ""
	elseif ori == "invisibility" then return ""
	elseif ori == "fiery hands" then return ""
	elseif ori == "earthen barrier" then return ""
	elseif ori == "shock hands" then return ""
	elseif ori == "inner power" then return ""
	elseif ori == "phase door" then return ""
	elseif ori == "teleport" then return ""
	elseif ori == "displacement shield" then return ""
	elseif ori == "probability travel" then return ""
	elseif ori == "arcane eye" then return ""
	elseif ori == "keen senses" then return ""
	elseif ori == "vision" then return ""
	elseif ori == "premonition" then return ""
	elseif ori == "arcane reconstruction" then return ""
	elseif ori == "shielding" then return ""
	elseif ori == "arcane shield" then return ""
	elseif ori == "aegis" then return ""
	elseif ori == "throw bomb" then return ""
	elseif ori == "alchemist protection" then return ""
	elseif ori == "explosion expert" then return ""
	elseif ori == "shockwave bomb" then return ""
	elseif ori == "fire infusion" then return ""
	elseif ori == "acid infusion" then return ""
	elseif ori == "lightning infusion" then return ""
	elseif ori == "frost infusion" then return ""
	elseif ori == "golem power" then return ""
	elseif ori == "golem resilience" then return ""
	elseif ori == "invoke golem" then return ""
	elseif ori == "golem portal" then return ""
	elseif ori == "life tap" then return ""
	elseif ori == "gem golem" then return ""
	elseif ori == "supercharge golem" then return ""
	elseif ori == "runic golem" then return ""
	elseif ori == "heat" then return ""
	elseif ori == "smoke bomb" then return ""
	elseif ori == "fire storm" then return ""
	elseif ori == "body of fire" then return ""
	elseif ori == "extract gems" then return ""
	elseif ori == "imbue item" then return ""
	elseif ori == "gem portal" then return ""
	elseif ori == "stone touch" then return ""
	elseif ori == "channel staff" then return ""
	elseif ori == "staff mastery" then return ""
	elseif ori == "defensive posture" then return ""
	elseif ori == "blunt thrust" then return ""
	elseif ori == "create minions" then return ""
	elseif ori == "aura mastery" then return ""
	elseif ori == "surge of undeath" then return ""
	elseif ori == "dark empathy" then return ""
	elseif ori == "undead explosion" then return ""
	elseif ori == "assemble" then return ""
	elseif ori == "sacrifice" then return ""
	elseif ori == "minion mastery" then return ""
	elseif ori == "invoke darkness" then return ""
	elseif ori == "circle of death" then return ""
	elseif ori == "fear the night" then return ""
	elseif ori == "rigor mortis" then return ""
	elseif ori == "shadow tunnel" then return ""
	elseif ori == "curse of the meek" then return ""
	elseif ori == "forgery of haze" then return ""
	elseif ori == "frostdusk" then return ""
	elseif ori == "blurred mortality" then return ""
	elseif ori == "impending doom" then return ""
	elseif ori == "undeath link" then return ""
	elseif ori == "lichform" then return ""
	elseif ori == "chill of the tomb" then return ""
	elseif ori == "will o' the wisp" then return ""
	elseif ori == "cold flames" then return ""
	elseif ori == "vampiric gift" then return ""
	elseif ori == "refit golem" then return ""
	elseif ori == "create alchemist gems" then return ""
	elseif ori == "necrotic aura" then return ""
	elseif ori == "teleport: angolwen" then return ""
	elseif ori == "water jet" then return ""
	-- wild gift
	elseif ori == "meditation" then return ""
	elseif ori == "nature's touch" then return ""
	elseif ori == "earth's eyes" then return ""
	elseif ori == "nature's balance" then return ""
	elseif ori == "waters of life" then return ""
	elseif ori == "elemental harmony" then return ""
	elseif ori == "one with nature" then return ""
	elseif ori == "healing nexus" then return ""
	elseif ori == "resolve" then return ""
	elseif ori == "aura of silence" then return ""
	elseif ori == "antimagic shield" then return ""
	elseif ori == "mana clash" then return ""
	elseif ori == "war hound" then return ""
	elseif ori == "jelly" then return ""
	elseif ori == "minotaur" then return ""
	elseif ori == "stone golem" then return ""
	elseif ori == "ritch flamespitter" then return ""
	elseif ori == "hydra" then return ""
	elseif ori == "rimebark" then return ""
	elseif ori == "fire drake" then return ""
	elseif ori == "turtle" then return ""
	elseif ori == "spider" then return ""
	elseif ori == "frantic summoning" then return ""
	elseif ori == "summon control" then return ""
	elseif ori == "rage" then return ""
	elseif ori == "detonate" then return ""
	elseif ori == "resilience" then return ""
	elseif ori == "phase summon" then return ""
	elseif ori == "master summoner" then return ""
	elseif ori == "grand arrival" then return ""
	elseif ori == "nature's cycle" then return ""
	elseif ori == "wild summon" then return ""
	elseif ori == "wild growth" then return ""
	elseif ori == "fungal growth" then return ""
	elseif ori == "ancestral life" then return ""
	elseif ori == "sudden growth" then return ""
	elseif ori == "swallow" then return ""
	elseif ori == "quake" then return ""
	elseif ori == "burrow" then return ""
	elseif ori == "sand breath" then return ""
	elseif ori == "bellowing roar" then return ""
	elseif ori == "wing buffet" then return ""
	elseif ori == "devouring flame" then return ""
	elseif ori == "fire breath" then return ""
	elseif ori == "ice claw" then return ""
	elseif ori == "ice skin" then return ""
	elseif ori == "ice wall" then return ""
	elseif ori == "ice breath" then return ""
	elseif ori == "lightning speed" then return ""
	elseif ori == "static field" then return ""
	elseif ori == "tornado" then return ""
	elseif ori == "lightning breath" then return ""
	elseif ori == "psiblades" then return ""
	elseif ori == "thorn grab" then return ""
	elseif ori == "leaves tide" then return ""
	elseif ori == "nature's equilibrium" then return ""
	elseif ori == "flamespit" then return ""
	elseif ori == "flame fury" then return ""
	elseif ori == "acid breath" then return ""
	elseif ori == "lightning breath" then return ""
	elseif ori == "poison breath" then return ""
	elseif ori == "winter's fury" then return ""
	elseif ori == "taunt" then return ""
	elseif ori == "shell shield" then return ""
	elseif ori == "web" then return ""
	elseif ori == "spit poison" then return ""
	-- corruption
	elseif ori == "drain" then return ""
	elseif ori == "bloodcasting" then return ""
	elseif ori == "absorb life" then return ""
	elseif ori == "life tap" then return ""
	elseif ori == "willful tormenter" then return ""
	elseif ori == "blood lock" then return ""
	elseif ori == "overkill" then return ""
	elseif ori == "blood vengeance" then return ""
	elseif ori == "soul rot" then return ""
	elseif ori == "vimsense" then return ""
	elseif ori == "leech" then return ""
	elseif ori == "dark portal" then return ""
	elseif ori == "bone spear" then return ""
	elseif ori == "bone grab" then return ""
	elseif ori == "bone nove" then return ""
	elseif ori == "bone shield" then return ""
	elseif ori == "pacification hex" then return ""
	elseif ori == "burning hex" then return ""
	elseif ori == "empathic hex" then return ""
	elseif ori == "domination hex" then return ""
	elseif ori == "curse of defenselessness" then return ""
	elseif ori == "curse of impotence" then return ""
	elseif ori == "curse of death" then return ""
	elseif ori == "curse of vulnerability" then return ""
	elseif ori == "virulent disease" then return ""
	elseif ori == "cyst burst" then return ""
	elseif ori == "catalepsy" then return ""
	elseif ori == "epidemic" then return ""
	elseif ori == "rend" then return ""
	elseif ori == "ruin" then return ""
	elseif ori == "acid strike" then return ""
	elseif ori == "dark surprise" then return ""
	elseif ori == "corrupted strength" then return ""
	elseif ori == "bloodlust" then return ""
	elseif ori == "carrier" then return ""
	elseif ori == "acid blood" then return ""
	elseif ori == "blood spray" then return ""
	elseif ori == "blood grasp" then return ""
	elseif ori == "blood boil" then return ""
	elseif ori == "blood fury" then return ""
	elseif ori == "dark ritual" then return ""
	elseif ori == "corrupted negation" then return ""
	elseif ori == "corrosive worm" then return ""
	elseif ori == "poison storm" then return ""
	elseif ori == "wraithform" then return ""
	elseif ori == "darkfire" then return ""
	elseif ori == "flame of urh'rok" then return ""
	elseif ori == "fearscape" then return ""
	-- cursed
	elseif ori == "slash" then return ""
	elseif ori == "frenzy" then return ""
	elseif ori == "reckless charge" then return ""
	elseif ori == "cleave" then return ""
	elseif ori == "stalk" then return ""
	elseif ori == "beckon" then return ""
	elseif ori == "harass prey" then return ""
	elseif ori == "surge" then return ""
	elseif ori == "dominate" then return ""
	elseif ori == "preternatural senses" then return ""
	elseif ori == "blindside" then return ""
	elseif ori == "repel" then return ""
	elseif ori == "gloom" then return ""
	elseif ori == "weakness" then return ""
	elseif ori == "dismay" then return ""
	elseif ori == "sanctuary" then return ""
	elseif ori == "rampage" then return ""
	elseif ori == "brutality" then return ""
	elseif ori == "tenacity" then return ""
	elseif ori == "slam" then return ""
	elseif ori == "mark prey" then return ""
	elseif ori == "anatomy" then return ""
	elseif ori == "outmaneuver" then return ""
	elseif ori == "mimic" then return ""
	elseif ori == "feed" then return ""
	elseif ori == "devour life" then return ""
	elseif ori == "feed power" then return ""
	elseif ori == "feed strengths" then return ""
	elseif ori == "willful strike" then return ""
	elseif ori == "deflection" then return ""
	elseif ori == "blast" then return ""
	elseif ori == "unseen force" then return ""
	elseif ori == "creeping darkness" then return ""
	elseif ori == "dark vision" then return ""
	elseif ori == "dark torrent" then return ""
	elseif ori == "dark tendrils" then return ""
	elseif ori == "call shadows" then return ""
	elseif ori == "shadow warriors" then return ""
	elseif ori == "shadow mages" then return ""
	elseif ori == "focus shadows" then return ""
	elseif ori == "reproach" then return ""
	elseif ori == "hateful whisper" then return ""
	elseif ori == "agony" then return ""
	elseif ori == "madness" then return ""
	elseif ori == "gesture of pain" then return ""
	elseif ori == "gesture of malice" then return ""
	elseif ori == "gesture of power" then return ""
	elseif ori == "gesture of guarding" then return ""
	elseif ori == "unnatural body" then return ""
	elseif ori == "relentless" then return ""
	elseif ori == "seethe" then return ""
	elseif ori == "grim resolve" then return ""
	elseif ori == "defiling touch" then return ""
	elseif ori == "dark gifts" then return ""
	elseif ori == "ruined earth" then return ""
	elseif ori == "cursed sentry" then return ""
	elseif ori == "instill fear" then return ""
	elseif ori == "heighten fear" then return ""
	elseif ori == "tyrant" then return ""
	elseif ori == "panic" then return ""
	elseif ori == "fade" then return ""
	elseif ori == "phase door" then return ""
	elseif ori == "blindside" then return ""
	elseif ori == "shadow lightning" then return ""
	elseif ori == "shadow flames" then return ""
	elseif ori == "reform" then return ""
	-- chronomancy
	elseif ori == "turn back the clock" then return ""
	elseif ori == "temporal fugue" then return ""
	elseif ori == "ashes to ashes" then return ""
	elseif ori == "body reversion" then return ""
	elseif ori == "precognition" then return ""
	elseif ori == "foresight" then return ""
	elseif ori == "moment of prescience" then return ""
	elseif ori == "spin fate" then return ""
	elseif ori == "energy decomposition" then return ""
	elseif ori == "entropic field" then return ""
	elseif ori == "energy absorption" then return ""
	elseif ori == "redux" then return ""
	elseif ori == "repulsion blast" then return ""
	elseif ori == "gravity spike" then return ""
	elseif ori == "repulsion field" then return ""
	elseif ori == "gravity well" then return ""
	elseif ori == "dust to dust" then return ""
	elseif ori == "carbon spikes" then return ""
	elseif ori == "destabilize" then return ""
	elseif ori == "quantum spike" then return ""
	elseif ori == "paradox mastery" then return ""
	elseif ori == "cease to exist" then return ""
	elseif ori == "fade from time" then return ""
	elseif ori == "paradox clone" then return ""
	elseif ori == "celerity" then return ""
	elseif ori == "stop" then return ""
	elseif ori == "slow" then return ""
	elseif ori == "haste" then return ""
	elseif ori == "strength of purpose" then return ""
	elseif ori == "invigorate" then return ""
	elseif ori == "quantum feed" then return ""
	elseif ori == "damage smearing" then return ""
	elseif ori == "gather the threads" then return ""
	elseif ori == "rethread" then return ""
	elseif ori == "temporal clone" then return ""
	elseif ori == "see the threads" then return ""
	elseif ori == "static history" then return ""
	elseif ori == "time skip" then return ""
	elseif ori == "echoes from the past" then return ""
	elseif ori == "temporal reprieve" then return ""
	elseif ori == "weapon folding" then return ""
	elseif ori == "swap" then return ""
	elseif ori == "displace damage" then return ""
	elseif ori == "temporal wake" then return ""
	elseif ori == "dimensional step" then return ""
	elseif ori == "banish" then return ""
	elseif ori == "wormhole" then return ""
	elseif ori == "spacetime mastery" then return ""
	elseif ori == "phase shot" then return ""
	elseif ori == "unerring shot" then return ""
	elseif ori == "perfect aim" then return ""
	elseif ori == "quick shot" then return ""
	elseif ori == "spacetime tuning" then return ""
	elseif ori == "anomaly teleport" then return ""
	elseif ori == "anomaly rearrange" then return ""
	elseif ori == "anomaly stop" then return ""
	elseif ori == "anomaly slow" then return ""
	elseif ori == "anomaly haste" then return ""
	elseif ori == "anomaly temporal storm" then return ""
	elseif ori == "anomaly summon time elemental" then return ""
	elseif ori == "anomaly temporal bubble" then return ""
	elseif ori == "anomaly dig" then return ""
	elseif ori == "anomaly swap" then return ""
	elseif ori == "anomaly gravity spike" then return ""
	elseif ori == "anomaly entropy" then return ""
	elseif ori == "anomaly summon townsfolk" then return ""
	elseif ori == "anomaly call" then return ""
	elseif ori == "anomaly flawed design" then return ""
	elseif ori == "anomaly dues ex" then return ""
	-- psionic
	elseif ori == "kinetic shield" then return ""
	elseif ori == "thermal shield" then return ""
	elseif ori == "charged shield" then return ""
	elseif ori == "absorption mastery" then return ""
	elseif ori == "kinetic aura" then return ""
	elseif ori == "thermal aura" then return ""
	elseif ori == "charged aura" then return ""
	elseif ori == "projection mastery" then return ""
	elseif ori == "telekinetic smash" then return ""
	elseif ori == "augmentation" then return ""
	elseif ori == "conduit" then return ""
	elseif ori == "frenzied psifighting" then return ""
	elseif ori == "mindlash" then return ""
	elseif ori == "pyrokinesis" then return ""
	elseif ori == "reach" then return ""
	elseif ori == "focused channeling" then return ""
	elseif ori == "mindhook" then return ""
	elseif ori == "quick as thought" then return ""
	elseif ori == "telekinetic leap" then return ""
	elseif ori == "shattering charge" then return ""
	elseif ori == "kinetic leech" then return ""
	elseif ori == "thermal leech" then return ""
	elseif ori == "charge leech" then return ""
	elseif ori == "insatiable" then return ""
	elseif ori == "perfect control" then return ""
	elseif ori == "reshape weapon" then return ""
	elseif ori == "reshape armour" then return ""
	elseif ori == "matter is energy" then return ""
	elseif ori == "aura discipline" then return ""
	elseif ori == "shield discipline" then return ""
	elseif ori == "iron will" then return ""
	elseif ori == "highly trained mind" then return ""
	elseif ori == "deflect projectiles" then return ""
	elseif ori == "bind" then return ""
	elseif ori == "implode" then return ""
	elseif ori == "greater telekinetic grasp" then return ""
	elseif ori == "mind storm" then return ""
	elseif ori == "feedback loop" then return ""
	elseif ori == "backlash" then return ""
	elseif ori == "focused wrath" then return ""
	elseif ori == "distortion bolt" then return ""
	elseif ori == "distortion wave" then return ""
	elseif ori == "ravage" then return ""
	elseif ori == "maelstrom" then return ""
	elseif ori == "forge shield" then return ""
	elseif ori == "forge bellows" then return ""
	elseif ori == "forge armor" then return ""
	elseif ori == "dreamforge" then return ""
	elseif ori == "dream smith's hammer" then return ""
	elseif ori == "hammer toss" then return ""
	elseif ori == "dream crusher" then return ""
	elseif ori == "forge echoes" then return ""
	elseif ori == "nightmare" then return ""
	elseif ori == "inner demons" then return ""
	elseif ori == "waking nightmare" then return ""
	elseif ori == "night terror" then return ""
	elseif ori == "mind sear" then return ""
	elseif ori == "psychic lobotomy" then return ""
	elseif ori == "synaptic static" then return ""
	elseif ori == "sunder mind" then return ""
	elseif ori == "slumber" then return ""
	elseif ori == "restless night" then return ""
	elseif ori == "sandman" then return ""
	elseif ori == "dreamscape" then return ""
	elseif ori == "solipsism" then return ""
	elseif ori == "balance" then return ""
	elseif ori == "clarity" then return ""
	elseif ori == "dismissal" then return ""
	elseif ori == "thought-forms" then return ""
	elseif ori == "thought-form: bowman" then return ""
	elseif ori == "thought-form: warrior" then return ""
	elseif ori == "thought-form: defender" then return ""
	elseif ori == "transcendent thought-forms" then return ""
	elseif ori == "over mind" then return ""
	elseif ori == "thought-form unity" then return ""
	elseif ori == "sleep" then return ""
	elseif ori == "lucid dreamer" then return ""
	elseif ori == "dream walk" then return ""
	elseif ori == "dream prison" then return ""
	elseif ori == "psychometry" then return ""
	elseif ori == "mental shielding" then return ""
	elseif ori == "projection" then return ""
	elseif ori == "mind link" then return ""
	elseif ori == "biofeedback" then return ""
	elseif ori == "resonance field" then return ""
	elseif ori == "amplification" then return ""
	elseif ori == "conversion" then return ""
	elseif ori == "telekinetic grasp" then return ""
	elseif ori == "beyond the flesh" then return ""
	-- race
	elseif ori == "gift of high born" then return ""
	elseif ori == "overseer of nations" then return ""
	elseif ori == "born into magic" then return ""
	elseif ori == "highborn's bloom" then return ""
	elseif ori == "grace of the eternals" then return ""
	elseif ori == "magic of the eternals" then return ""
	elseif ori == "secrets of the eternals" then return ""
	elseif ori == "timeless" then return ""
	elseif ori == "wrath of the woods" then return ""
	elseif ori == "unshackled" then return ""
	elseif ori == "guardian of the wood" then return ""
	elseif ori == "nature's pride" then return ""
	elseif ori == "luck of the little folk" then return ""
	elseif ori == "duck and dodge" then return ""
	elseif ori == "millitant mind" then return ""
	elseif ori == "indomitable" then return ""
	elseif ori == "resilience of the dwarves" then return ""
	elseif ori == "stoneskin" then return ""
	elseif ori == "power is money" then return ""
	elseif ori == "stone walking" then return ""
	elseif ori == "dominant will" then return ""
	elseif ori == "unity" then return ""
	elseif ori == "quickened" then return ""
	elseif ori == "wayist" then return ""
	elseif ori == "knowledge of the way" then return ""
	elseif ori == "knowledge of the past" then return ""
	elseif ori == "ghoul" then return ""
	elseif ori == "ghoulish leap" then return ""
	elseif ori == "retch" then return ""
	elseif ori == "gnaw" then return ""
	elseif ori == "skeleton" then return ""
	elseif ori == "bone armour" then return ""
	elseif ori == "resilient bones" then return ""
	elseif ori == "re-assemble" then return ""
	-- inscription
	elseif ori == "infusion of regeneration" then return ""
	elseif ori == "infusion of healing" then return ""
	elseif ori == "infusion of wild" then return ""
	elseif ori == "infusion of movement" then return ""
	elseif ori == "infusion of sun" then return ""
	elseif ori == "infusion of heroism" then return ""
	elseif ori == "infusion of insidious poison" then return ""
	elseif ori == "infusion of wilf growth " then return ""
	elseif ori == "rune of phase door" then return ""
	elseif ori == "rune of controlled phase door" then return ""
	elseif ori == "rune of teleportation" then return ""
	elseif ori == "rune of shielding" then return ""
	elseif ori == "rune of reflection shield" then return ""
	elseif ori == "rune of invisibility" then return ""
	elseif ori == "rune of speed" then return ""
	elseif ori == "rune of vision" then return ""
	elseif ori == "rune of heat beam" then return ""
	elseif ori == "rune of frozen spear" then return ""
	elseif ori == "rune of acid wave" then return ""
	elseif ori == "rune of lightning" then return ""
	elseif ori == "rune of manasurge " then return ""
	
	else return str end
	
	
end

function string.krTalentType(str)
	local ori = str:lower()
	if ori == "technique" then return "물리"
	elseif ori == "celestial" then return "천공"
	elseif ori == "chronomancy" then return "시공"
	elseif ori == "corruption" then return "타락"
	elseif ori == "cunning" then return "교활"
	elseif ori == "cursed" then return "저주"
	elseif ori == "wild-gift" then return "자연의 권능"
	elseif ori == "base" then return "기본"
	elseif ori == "inscriptions" then return "각인"
	elseif ori == "race" then return "종족"
	elseif ori == "tutorial" then return "입문"
	elseif ori == "psionic" then return "초능력"
	elseif ori == "spell" then return "주문"
	elseif ori == "undead" then return "언데드"
	-- misc
	elseif ori == "class" then return "직업"
	elseif ori == "race" then return "종족"
	elseif ori == "higher" then return "하이어"
	elseif ori == "shalore" then return "샬로레"
	elseif ori == "thalore" then return "탈로레"
	elseif ori == "halfling" then return "하플링"
	elseif ori == "dwarf" then return "드워프"
	elseif ori == "ghoul" then return "구울"
	elseif ori == "skeleton" then return "스켈레톤"
	elseif ori == "yeek" then return "이크"
	elseif ori == "inscriptions" then return "각인"
	elseif ori == "infusions" then return "인퓨전"
	elseif ori == "runes" then return "룬"
	elseif ori == "taints" then return "얼룩"
	elseif ori == "horror" then return "공포"
	elseif ori == "objects" then return "물체"
	elseif ori == "other" then return "기타"
	---- celestial
	elseif ori == "guardian" then return "빛의 수호자"
	elseif ori == "chants" then return "태양의 찬가"
	elseif ori == "light" then return "빛"
	elseif ori == "combat" then return "빛의 전투"
	elseif ori == "sun" then return "태양"
	elseif ori == "glyphs" then return "문양"
	elseif ori == "twilight" then return "황혼"
	elseif ori == "star fury" then return "별의 분노"
	elseif ori == "hymns" then return "달의 송가"
	elseif ori == "circles" then return "권역"
	elseif ori == "eclipse" then return "금환식"
	-- uber
	elseif ori == "strength" then return "힘"
	elseif ori == "dexterity" then return "민첩"
	elseif ori == "constitution" then return "체격"
	elseif ori == "magic" then return "마법"
	elseif ori == "willpower" then return "의지"
	elseif ori == "cunning" then return "교활"
	-- undeads
	elseif ori == "ghoul" then return "구울"
	elseif ori == "skeleton" then return "스켈레톤"
	elseif ori == "vampire" then return "뱀파이어"
	elseif ori == "lich" then return "리치"
	-- techniques
	elseif ori == "two-handed weapons" then return "양손무기 공격기술"
	elseif ori == "two-handed maiming" then return "양손무기 제압기술"
	elseif ori == "shield offense" then return "방패 공격기술"
	elseif ori == "shield defense" then return "방패 방어기술"
	elseif ori == "dual weapons" then return "쌍수 무기 숙련"
	elseif ori == "dual techniques" then return "쌍수 무기 공격기술"
	elseif ori == "archery - base" then return "사격기술 - 기본"
	elseif ori == "archery - bows" then return "사격기술 - 활"
	elseif ori == "archery - slings" then return "사격기술 - 투석구"
	elseif ori == "archery training" then return "사격기술 숙련"
	elseif ori == "archery prowess" then return "사격기술 - 고급"
	elseif ori == "superiority" then return "전투 압도기술"
	elseif ori == "battle tactics" then return "전술 행동"
	elseif ori == "warcries" then return "전투 함성"
	elseif ori == "bloodthirst" then return "피의 갈망"
	elseif ori == "field control" then return "전장 제어"
	elseif ori == "combat techniques" then return "전투 기술"
	elseif ori == "combat veteran" then return "전투 숙련"
	elseif ori == "combat training" then return "전투장비 숙련"
	elseif ori == "magical combat" then return "마법 전투기술"
	elseif ori == "mobility" then return "기동성"
	elseif ori == "thuggery" then return "무법자의 전투기술"
	elseif ori == "pugilism" then return "권투 기술"
	elseif ori == "finishing moves" then return "마무리 공격"
	elseif ori == "grappling" then return "잡기기술"
	elseif ori == "unarmed discipline" then return "맨손전투 고급기술 "
	elseif ori == "unarmed training" then return "맨손전투 숙련"
	elseif ori == "conditioning" then return "신체 조절"
	elseif ori == "unarmed other" then return "기타 맨손 기술"
	-- chronomancy
	elseif ori == "age manipulation" then return "시간 조작"
	elseif ori == "chronomancy" then return "시공"
	elseif ori == "energy" then return "에너지"
	elseif ori == "gravity" then return "중력"
	elseif ori == "matter" then return "물질"
	elseif ori == "paradox" then return "괴리"
	elseif ori == "speed control" then return "속도 조절"
	elseif ori == "temporal combat" then return "시간 전투기술"
	elseif ori == "timeline threading" then return "시간축 연결"
	elseif ori == "timetravel" then return "시간여행"
	elseif ori == "spacetime folding" then return "시공간 접기"
	elseif ori == "spacetime weaving" then return "시공간 엮기"
	elseif ori == "temporal archery" then return "시간 사격기술"
	elseif ori == "anomalies" then return "이상현상"
	-- corruptions
	elseif ori == "sanguisuge" then return "생명력 조작"
	elseif ori == "torment" then return "고통"
	elseif ori == "vim" then return "활력 조작"
	elseif ori == "bone" then return "해골 조작"
	elseif ori == "hexes" then return "매혹술"
	elseif ori == "curses" then return "저주"
	elseif ori == "plague" then return "질병"
	elseif ori == "scourge" then return "재앙"
	elseif ori == "reaving combat" then return "약탈 전투기술"
	elseif ori == "blood" then return "타락의 피"
	elseif ori == "blight" then return "황폐"
	elseif ori == "shadowflame" then return "어둠의 열화"
	-- cunning
	elseif ori == "stealth" then return "은신"
	elseif ori == "trapping" then return "함정"
	elseif ori == "traps" then return "함정"
	elseif ori == "poisons" then return "중독"
	elseif ori == "dirty fighting" then return "비열한 전투기술"
	elseif ori == "lethality" then return "치명상"
	elseif ori == "shadow magic" then return "그림자 마법"
	elseif ori == "ambush" then return "매복"
	elseif ori == "survival" then return "생존기술"
	elseif ori == "tactical" then return "전략"
	elseif ori == "scoundrel" then return "무뢰배 기술"
	-- cursed
	elseif ori == "slaughter" then return "대학살"
	elseif ori == "endless hunt" then return "끝없는 사냥"
	elseif ori == "strife" then return "투쟁"
	elseif ori == "gloom" then return "침울한 기운"
	elseif ori == "rampage" then return "난폭"
	elseif ori == "predator" then return "약탈자"
	elseif ori == "dark sustenance" then return "어둠의 생명유지"
	elseif ori == "force of will" then return "의지의 힘"
	elseif ori == "darkness" then return "어둠"
	elseif ori == "shadows" then return "그림자"
	elseif ori == "punishments" then return "처단"
	elseif ori == "gestures" then return "저주받은 몸짓"
	elseif ori == "cursed form" then return "저주받은 형상"
	elseif ori == "cursed aura" then return "저주받은 기운"
	elseif ori == "curses" then return "저주"
	elseif ori == "fears" then return "공포"
	-- wild gifts
	elseif ori == "call of the wild" then return "야생의 부름"
	elseif ori == "harmony" then return "조화"
	elseif ori == "antimagic" then return "반마법"
	elseif ori == "summoning (melee)" then return "소환 (근거리)"
	elseif ori == "summoning (distance)" then return "소환 (장거리)"
	elseif ori == "summoning (utility)" then return "소환 (유용)"
	elseif ori == "summoning (augmentation)" then return "소환기술 향상"
	elseif ori == "summoning (advanced)" then return "소환 (숙련)"
	elseif ori == "slime aspect" then return "슬라임 형태"
	elseif ori == "fungus" then return "미생물"
	elseif ori == "sand drake aspect" then return "모래 드레이크 형태"
	elseif ori == "fire drake aspect" then return "화염 드레이크 형태"
	elseif ori == "cold drake aspect" then return "냉기 드레이크 형태"
	elseif ori == "storm drake aspect" then return "폭풍 드레이크 형태"
	elseif ori == "venom drake aspect" then return "독성 드레이크 형태"
	elseif ori == "higher draconic abilities" then return "드라코닉 고등기술"
	elseif ori == "mindstar mastery" then return "마석 숙달"
	elseif ori == "mucus" then return "점액"
	elseif ori == "ooze" then return "발산"
	elseif ori == "malleable body" then return "유연한 신체"
	-- psionic
	elseif ori == "absorption" then return "충격 흡수"
	elseif ori == "projection" then return "오러"
	elseif ori == "psi-fighting" then return "염력 전투기술"
	elseif ori == "focus" then return "집중"
	elseif ori == "augmented mobility" then return "증대된 기동성"
	elseif ori == "voracity" then return "폭식"
	elseif ori == "finer energy manipulations" then return "향상된 에너지 조작"
	elseif ori == "mental discipline" then return "정신 훈련"
	elseif ori == "grip" then return "잡기기술"
	elseif ori == "psi-archery" then return "염력 궁술"
	elseif ori == "greater psi-fighting" then return "상위 염력 전투기술"
	elseif ori == "brainstorm" then return "창조적 생각"
	elseif ori == "discharge" then return "방출"
	elseif ori == "distortion" then return "왜곡"
	elseif ori == "dream forge" then return "꿈의 연마장"
	elseif ori == "dream smith" then return "꿈의 망치"
	elseif ori == "nightmare" then return "악몽"
	elseif ori == "psychic assault" then return "염동 공격"
	elseif ori == "slumber" then return "졸음 기술"
	elseif ori == "solipsism" then return "유아론"
	elseif ori == "thought-forms" then return "사념의 형상"
	elseif ori == "dreaming" then return "꿈의 기술"
	elseif ori == "mentalism" then return "유심론"
	elseif ori == "feedback" then return "반작용"
	elseif ori == "trance" then return "최면"
	elseif ori == "possession" then return "소유"
	-- spells
	elseif ori == "arcane" then return "비밀의 힘"
	elseif ori == "aether" then return "아이테르"
	elseif ori == "fire" then return "화염"
	elseif ori == "wildfire" then return "염화"
	elseif ori == "earth" then return "땅"
	elseif ori == "stone" then return "돌"
	elseif ori == "water" then return "물"
	elseif ori == "ice" then return "얼음"
	elseif ori == "air" then return "공기"
	elseif ori == "storm" then return "폭풍"
	elseif ori == "meta" then return "메타"
	elseif ori == "temporal" then return "시간"
	elseif ori == "phantasm" then return "환영"
	elseif ori == "enhancement" then return "강화"
	elseif ori == "conveyance" then return "전도"
	elseif ori == "divination" then return "예견"
	elseif ori == "aegis" then return "보호"
	elseif ori == "explosive" then return "폭발"
	elseif ori == "infusion" then return "주입"
	elseif ori == "golemancy" then return "골렘술"
	elseif ori == "advanced golemancy" then return "고급 골렘술"
	elseif ori == "fire alchemy" then return "불의 연금술"
	elseif ori == "stone alchemy" then return "돌의 연금술"
	elseif ori == "staff combat" then return "지팡이 전투기술"
	elseif ori == "necrotic minions" then return "사령의 추종자"
	elseif ori == "advanced necrotic minions" then return "고급 사령의 추종자"
	elseif ori == "nightfall" then return "밤의 몰락"
	elseif ori == "shades" then return "그늘"
	elseif ori == "necrosis" then return "사령술"
	elseif ori == "grave" then return "무덤"

	else return str end
end

function string.krRace(str)
	local ori = str:lower()
	if ori == "construct" then return "구조체"
	elseif ori == "Runic Golem" then return "룬 골렘"
	elseif ori == "dwarf" then return "드워프"
	elseif ori == "elf" then return "엘프"
	elseif ori == "shalore" then return "샬로레"
	elseif ori == "thalore" then return "탈로레"
	elseif ori == "halfling" then return "하플링"
	elseif ori == "human" then return "인간"
	elseif ori == "cornac" then return "코르낙"
	elseif ori == "higher" then return "하이어"
	elseif ori == "tutorial human" then return "연습게임용 인간"
	elseif ori == "tutorial base" then return "연습게임용 종족"
	elseif ori == "tutorial stats" then return "연습게임용 능력자"
	elseif ori == "undead" then return "언데드"
	elseif ori == "ghoul" then return "구울"
	elseif ori == "skeleton" then return "스켈레톤"
	elseif ori == "yeek" then return "이크"
	else return str end
end

function string.krClass(str)
	local ori = str:lower()
	if ori == "technique" then return "물리"
	elseif ori == "higher" then return "하이어"
	elseif ori == "adventurer" then return "모험가"
	elseif ori == "afflicted" then return "고통받는 자"
	elseif ori == "cursed" then return "저주받은 자"
	elseif ori == "doomed" then return "파멸당한 자"
	elseif ori == "celestial" then return "천공의 사도"
	elseif ori == "sun paladin" then return "태양의 기사"
	elseif ori == "anorithil" then return "아노리실"
	elseif ori == "chronomancer" then return "시공 제어사"
	elseif ori == "paradox mage" then return "괴리 마법사"
	elseif ori == "temporal warden" then return "시간의 감시자"
	elseif ori == "defiler" then return "모독자"
	elseif ori == "reaver" then return "파괴자"
	elseif ori == "curruptor" then return "타락자"
	elseif ori == "mage" then return "마법사"
	elseif ori == "alchemist" then return "연금술사"
	elseif ori == "archmage" then return "대마법사"
	elseif ori == "necromancer" then return "사령술사"
	elseif ori == "none" then return "없음"
	elseif ori == "psionic" then return "초능력자"
	elseif ori == "mindslayer" then return "정신 파괴자"
	elseif ori == "solipsist" then return "유아론자"
	elseif ori == "rogue" then return "도적"
	elseif ori == "shadowblade" then return "쉐도우블레이드"
	elseif ori == "marauder" then return "약탈자"
	elseif ori == "tutorial adventurer" then return "초보자 입문용 모험가"
	elseif ori == "warrior" then return "전사"
	elseif ori == "berserker" then return "광전사"
	elseif ori == "bulwark" then return "수호자"
	elseif ori == "archer" then return "궁수"
	elseif ori == "arcane blade" then return "마법 전사"
	elseif ori == "brawler" then return "격투가"
	elseif ori == "wilder" then return "자연의 추종자"
	elseif ori == "summoner" then return "소환술사"
	elseif ori == "wyrmic" then return "워믹"
	else return str end
end
